version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: expenses-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: expenses_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - expenses-net

volumes:
  mysql_data:

networks:
  expenses-net:
